In [2]:
import torch
from torch.autograd import Variable

In [3]:
a = Variable(torch.ones(2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [5]:
b = Variable(torch.ones(2,2), requires_grad=True)

In [6]:
b

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
print(a*b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [8]:
print(torch.mul(a,b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
